branches:
    only:
        - master

sudo: required
dist: trusty
group: deprecated-2017Q2

services:
    - memcached
    - redis

language: python
python:
    - "2.7"
    - "3.4"

virtualenv:
    system_site_packages: true

before_install:
    - sudo add-apt-repository -y ppa:reddit/ppa
    - echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
    - sudo apt-key add puppet/modules/cassandra/files/repo_key
    - sudo apt-get update -q
    - >
        sudo apt-get install -y \
            cassandra=2.2.8 \
            fbthrift-compiler \
            make \
            pylint \
            python \
            python3 \
            python3-cassandra \
            python3-coverage \
            python3-cqlmapper \
            python3-fbthrift \
            python3-gevent \
            python3-hvac \
            python3-jwt \
            python3-kazoo \
            python3-kombu \
            python3-nose \
            python3-posix-ipc \
            python3-pymemcache \
            python3-redis \
            python3-requests \
            python3-setuptools \
            python3-sqlalchemy \
            python3-webtest \
            python-alabaster \
            python-coverage \
            python-cqlmapper \
            python-cryptography \
            python-enum34 \
            python-fbthrift \
            python-flake8 \
            python-gevent \
            python-hvac \
            python-jwt \
            python-kazoo \
            python-kombu \
            python-mock \
            python-nose \
            python-posix-ipc \
            python-pymemcache \
            python-pyramid \
            python-redis \
            python-requests \
            python-setuptools \
            python-sphinx \
            python-sphinxcontrib.spelling \
            python-sqlalchemy \
            python-webtest \
            unzip \
            zookeeperd
    - sudo service cassandra start
    - wget https://releases.hashicorp.com/vault/0.7.3/vault_0.7.3_linux_amd64.zip && unzip vault_0.7.3_linux_amd64.zip && ./vault server -dev -dev-root-token-id=b4c6f298-3f80-11e7-8b88-5254001e7ad3 &
    - sleep 10  # cassandra takes a while to start up

script:
    - make
    - nosetests -v
    - sphinx-build -M doctest docs/ build/
    - sphinx-build -M spelling docs/ build/
    - make lint
deploy:
  provider: pypi
  user: cshoe
  password:
    secure: Xon+rSBd4OqwGfWaNfiHwhyBXNioVTC20k14VNIWDySdGi2iVSsQtzN2sqmyDAv7Wx8Fs7/4SSqAthQ8yg/8uOtadcgcalRg9UzaWd/yf5wUGWaH0voocq3gyCDGUrp8tMt8xfaflr7WLN6EOdtVUzpaHjVG6m1wyb7m/R9jdy5hj+b1xzNJB9NDkUHbPIvtpxdY+lrU1401XF0ET9Wog4nmxAFjjkLlLUJ8d+zg+WG830chGzPOq6OZ0pfxTy2b2abpgtZbuaH3nVV0w7eXSTAf4Cub2Fv7VpbL+DXUOKgsNmvAjwm23HAs+7qIWlxDXXpuG5Mnvn7r07I/tkhN+TdAQrpA3/VJ/iUYOxiGJZ1EMGgbPnH4YKNoAIEUvunxCvFanD+iSe+u1oyzlu81aoR+p2MubeER1OGIOzjX+GU6t61QImEUP6CuhRh5E5QnRvAMDplAWpdR8F4DgRDoYgYiCOCLFOSaKFEDTYjW6tJ8BK6tY3mzAEM3PkeyhXQWBdrHrxJ0KJe6WhRnJ39AuDIZfG3bT5rO361UKGUNZ+Y9+NF3FRvfwLzqeTE0PrHHoiLKhZOvnwEwmw2n1yxgYj5RqkIlYESs9KocoivEGKhOclGJkBfM2xYLaJXFyhEU2nrQLO1AxzqFtc+cY6z0gymjPgdMhyGYhKx9qOY83KQ=
  on:
    tags: true
